import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Building2,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  CircleCheck,
  CircleX,
  FileText,
  GripVertical,
  IndentDecrease,
  IndentIncrease,
  Info,
  List,
  ListChecks,
  ListOrdered,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Pencil,
  Phone,
  Plus,
  Printer,
  RemoveFormatting,
  Trash2,
  TriangleAlert,
  User,
  X,
} from 'lucide-react'

/** Legacy Material Symbol names → Lucide components (RichEditor toolbar). */
export const ICONS = {
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  add: Plus,
  close: X,
  print: Printer,
  edit: Pencil,
  description: FileText,
  warning: TriangleAlert,
  check_circle: CircleCheck,
  error: CircleX,
  info: Info,
  forum: MessageSquare,
  call: Phone,
  mail: Mail,
  domain_add: Building2,
  person: User,
  drag_indicator: GripVertical,
  unfold_more: ChevronsDown,
  unfold_less: ChevronsUp,
  keyboard_arrow_right: ChevronRight,
  keyboard_arrow_down: ChevronDown,
  checklist: ListChecks,
  delete: Trash2,
  format_align_left: AlignLeft,
  format_align_center: AlignCenter,
  format_align_right: AlignRight,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_indent_increase: IndentIncrease,
  format_indent_decrease: IndentDecrease,
  format_clear: RemoveFormatting,
  more_horiz: MoreHorizontal,
  done_outline: CheckCircle2,
}

/** @deprecated Import Lucide icons directly in new code. */
export function getIcon(name) {
  return ICONS[name] ?? null
}
